### ISSUE TITLE
MacOS: valetudo-helper-miioota-amd64: cannot execute binary file

### ISSUE THREAD

**Issue by antoinetielbeke** [Hypfer/valetudo-helper-miioota#11]
I'm trying to make this work on my mac but no luck so far:

Downloaded the amd64 file, used `chmod +x valetudo-helper-miioota-amd64` but I end up with:

```
sudo ./valetudo-helper-miioota-amd64
./valetudo-helper-miioota-amd64: ./valetudo-helper-miioota-amd64: cannot execute binary file
``` 

Any ideas?

**Comment by Hypfer** [comment]
You're trying to run a Linux binary on a mac. That doesn't work

Mac is not and will not be supported.
Binaries are available for Linux and Windows-based hosts

**Comment by antoinetielbeke** [comment]
Thanks for the reply. I think the sneer at the end was not necessary but okay. Thanks for your work so far.
