### ISSUE TITLE
Why delete my issue?

### ISSUE THREAD

**Issue by cuesir** [Hypfer/valetudo-helper-miioota#16]
I'm going to post one more time as I don't know why you deleted my previous issue report. Feel free to delete this as well if you feel it is irrelevant then I'll stop bothering you.

This is for 
Roborock V1 also known as the Xiaomi Mi Robot Vacuum (made before 2020-03)
Wyze Robot Vacuum is a rebranded Xiaomi Mi Robot Vacuum and it is also made before 2020-03 (I believe I read the information properly so I posted and joined your project)

Issue: Miioota looking for 192.168.8.1
Wyze Robot Vacuum WLAN network 192.168.5.1

Miioota Error, looking for devices on 192.168.8.1 unable to find any robots.

**Comment by Hypfer** [comment]
> Wyze Robot Vacuum is a rebranded Xiaomi Mi Robot Vacuum

Nope. It isn't.
This is not the right tool for the job.
