### ISSUE TITLE
ERROR: Did not receive a firmware download request after 30s

### ISSUE THREAD

**Issue by marthinx** [Hypfer/valetudo-helper-miioota#18]
I can not flash my Roborock S5.
This it the output. Is it correct that it is waiting for a different IP address?
Thank you for help

Output:
martin@XiaomiMint:~/Downloads$ ./valetudo-helper-miioota-amd64 install-firmware v11_002008.pkg 
Starting installer.
If you experience issues, make sure to disable your firewall and/or VPN.
Also, make sure that the robot is docked during the firmware update procedure.
If the install still fails, try turning the robot off and back on again and/or moving the laptop closer to it.

Robot discovery started...
Scan done.
Successfully discovered robot at 192.168.8.1
Reading firmware image..
Successfully read firmware image. Size: 74.52 MiB MD5Sum: 54a353469470583e10d4e874cb5caa7c

**Listing for firmware download requests on http://192.168.8.88:46377/firmware**
Response from robot: [ 'ok' ]
ERROR: Did not receive a firmware download request after 30s

Exiting..
martin@XiaomiMint:~/Downloads$

**Comment by Hypfer** [comment]
#2
#13
