### ISSUE TITLE
ERROR: Did not receive a firmware download request

### ISSUE THREAD

**Issue by nl2299** [Hypfer/valetudo-helper-miioota#2]
Hi,
'm trying to flash a used roborock s5 with valetudo.
Steps for installing:
1.) create image with the dustbuilder 
2.) reset robot
3.) connect laptop (windows) to roborock AP
4.) start the valetudo helper
following error message i got
```

Robot discovery started...
Scan done.
Successfully discovered robot at 192.168.8.1
Reading firmware image..
Successfully read firmware image. Size: 78.63 MiB MD5Sum: 3610f3611b884836533f9cc03d688b1f

Listing for firmware download requests on http://192.168.8.42:57185/firmware
Response from robot: [ 'ok' ]
ERROR: Did not receive a firmware download request after 30s
```

After the script ends the power led of the robot flash around 30 sec and if I press it the robot says "please wait while im finishing update" after that robot is usable again but doesn't reboot and valetudo seams also to not installed. 
If I try it without the robot on the charger it says "please charge"

Maybe I used the wrong dustbuilder image especially the step "Select the version of the generated firmware:" makes my a bit confused as i don't know which version is currently installed on the vacuum as i never paired it with the app. I just user 2034

**Comment by Hypfer** [comment]
Did you also read and follow the troubleshooting instructions logged by the installer right before the part that you've pasted?

```
Starting installer.
If you experience issues, make sure to disable your firewall and/or VPN.
Also, make sure that the robot is docked during the firmware update procedure.
If the install still fails, try turning the robot off and back on again and/or moving the laptop closer to it.
 
```
