### ISSUE TITLE
Exec format error on VM Ubuntu 20.04.2

### ISSUE THREAD

**Issue by Patr-ick** [Hypfer/valetudo-helper-miioota#4]
Running a virtual machine with Ubuntu 20.04.2 ARM64 on a M1 Macbook Pro, which file do I need? tried all three but received `cannot execute binary file: Exec format error`
Do I have to compile my own executable version with the source code?

**Comment by Gobbomaster** [comment]
Hi @Patr-ick , can you share what you did to solve your problem? Tried all three on a Macbook Pro 2015 (default terminal, expected to have needed valetudo-helper-miioota-amd64) but it refuses to do anything.

**Comment by Patr-ick** [comment]
Hey @Gobbomaster, I've ended up flashing the vaccum robot without the helper-miioota tool, since I couldn't get it to work either.
