### ISSUE TITLE
"Download seems to have finished" reported, downloads is not finished

### ISSUE THREAD

**Issue by TheNitek** [Hypfer/valetudo-helper-miioota#5]
I am trying to install valetudo on my V1 using my Windows PC, but the installation fails:
A few seconds after `Received firmware download request from ::ffff:192.168.8.1..` the message `Download seems to have finished.` is shown. There is now way that there is enough time elapsed to transfer the 120MB firmware.
Looking at the amount of data transfered over my wifi interface, I also see a few MB at best transfered. Keeping a look at the interface there still seems to be data transfer ongoing even after valetudo-helper-miioota has already exited.

The robot also seems to keep updating for a while until finishing with a chinese voice message, but no valetudo seems to be installed. Is there mybe another way to track the progress/success of the firmware download?

**Comment by Hypfer** [comment]
Not that I'm aware of.

Please make sure to follow the troubleshooting guidance printed by the program itself.

```
If you experience issues, make sure to disable your firewall and/or VPN.
Also, make sure that the robot is docked during the firmware update procedure.
If the install still fails, try turning the robot off and back on again and/or moving the laptop closer to it.
```

Furthermore, make sure that you're not trying to flash a tar.gz
You need to build a .pkg file using the dustbuilder

**Comment by TheNitek** [comment]
> Furthermore, make sure that you're not trying to flash a tar.gz You need to build a .pkg file using the dustbuilder

THIS is probably were I messed up, thx.

**Comment by TheNitek** [comment]
Using the .pkg I managed to install valetudo now. valetudo-helper-miioota still ended while the download was still running.
