### ISSUE TITLE
Windows: valetudo exe will close after execution

### ISSUE THREAD

**Issue by fakio87** [Hypfer/valetudo-helper-miioota#8]
Hi, I tried to start the exe of the latest release on 4 different machines running windows 11, windows 10, windows 7.

On every machine after starting the exe (from explorer or cmd) a new terminal window will show up but close initially.

I receive no log gile or anything to troubleshoot.

Also older versions do not execute.

Any idea what I am doing wrong?

**Comment by Hypfer** [comment]
It's a command-line application.

> Simply download the latest binary [from the releases section](https://github.com/Hypfer/valetudo-helper-miioota/releases) **and execute it in a terminal/powershell window.**
