### ISSUE TITLE
[Feature Request] Option to set the IP of the device

### ISSUE THREAD

**Issue by stranno** [Hypfer/valetudo-helper-miioota#9]
If I'm not wrong, IP is hardcoded to 192.168.8.0-254 range. Is there any chance to add IP parameter to set the IP of the device or at least a different range? I'm using 192.168.0.XXX and I don't see any option, unlike the mirobot tool, for example.

**Comment by Hypfer** [comment]
That would make no sense as this tool is exclusively used to flash an unprovisioned roborock s5 or v1 with an old enough firmware. It will always be this exact IP.

**Comment by stranno** [comment]
I have a Mi Robot Vacuum Gen 1, SDJQR02RR, and it looks like this in the router.

![image](https://user-images.githubusercontent.com/6293197/193807498-c40f203f-9414-48c6-8bab-b42de8a83fa9.png)

And this is what the tool says.

> ERROR: There's no network interface with an IPv4 address in 192.168.8.0/24.
> We're not connected to the robots Wi-Fi Access Point

**Comment by Hypfer** [comment]
It should not be connected to the router if you want to use this tool.
You need to do a full factory reset first and then connect to the Wi-Fi AP provided by the robot

See also
https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Robots-Factory-Reset
